{{- if .Values.dbInit.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: movie-db-init
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: psql
          image: postgres:15
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: sql
              mountPath: /sql
          command:
            - sh
            - -c
          args:
            - |
              echo "⏳ Waiting for database..."
              sleep 20

              psql "host={{ .Values.backend.env.DB_HOST }} user={{ .Values.dbInit.user }} dbname=postgres sslmode=require" -f /sql/init.sql
      volumes:
        - name: sql
          configMap:
            name: movie-db-init-sql
{{- end }}
